# Generated by Django 4.1.5 on 2023-02-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_fbhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='colores',
            field=models.CharField(default='', max_length=40),
        ),
    ]
