# Generated by Django 4.1.5 on 2023-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_fbhub', '0003_estadio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(default='fbhub/media/No-Image-Placeholder.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen',
            field=models.ImageField(default='fbhub/media/No-Image-Placeholder.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(default='fbhub/media/No-Image-Placeholder.jpg', upload_to='media/'),
        ),
    ]
