# Generated by Django 4.1.5 on 2023-03-05 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_fbhub', '0004_equipo_escudo_estadio_imagen_jugador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(default='media/No-Image-Placeholder.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='imagen',
            field=models.ImageField(default='media/No-Image-Placeholder.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(default='media/No-Image-Placeholder.jpg', upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
