# Generated by Django 4.1.5 on 2023-03-10 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_fbhub', '0008_estadio_equipo_jugador_equipo_act_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='pie_fav',
            field=models.CharField(choices=[('Izquierdo', 'Izquierdo'), ('Derecho', 'Derecho')], max_length=9),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
