# Generated by Django 4.1.5 on 2023-03-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_fbhub', '0009_alter_jugador_pie_fav_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='App_fbhub.equipo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='estadio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='App_fbhub.estadio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='App_fbhub.jugador'),
        ),
    ]
